10.10.2022 is start of the WS not 04.10.
pep-dortmund/homepage-toolbox pull request #186
Opened 2022-05-18 10:27 UTC by chrbeckm

2022-05-29 09:44 UTC, jpherdi requested changes
Neben den inline Kommentaren:

Neben Hybrid sollte am besten auch schon ein Raum genannt werden wenn möglich?

Und im Protokoll hieß es, die Räume sind erst angefragt? Sollten wir die nicht erst auf der Website veröffentlichen, wenn die auch bestätigt sind?

2022-05-29 09:44 UTC, jpherdi commented on index.md
> +Der Eingang befindet sich gegenüber vom Hörsaalgebäude II.
Vielleicht besser: "Der Eingang befindet sich gegenüber vom Haupteingang des Hörsaalgebäudes II."

Ich denke, dass gerade für Physik-Studierende das HS II eher als Teil des Physikgebäudes wahrgenommen werden könnte und nicht klar ist, was du mit "gegenüber" meinst.

2022-05-29 09:44 UTC, jpherdi commented on index.md
> +  <td><span style="color:crimson"> ZE HS 02</span></td>
Wieso die besondere Farbe?

2022-05-30 06:40 UTC, chrbeckm commented on index.md
> +  <td><span style="color:crimson"> ZE HS 02</span></td>
Hatten wir früher auch gemacht, wenn der Hörsaal für einen Tag gewechselt werden musste.

2022-05-30 06:42 UTC, chrbeckm commented
Zum Installationsraum: Guter Punkt, ich war mir nicht sicher ob wir uns dort die Option offen halten wollen einen größeren Raum zu nehmen, wenn die Nachfrage höher ist.

Zu den Hörsälen: Die Reservierungen sind mittlerweile vom Dez. 6 im LSF eingetragen.

2022-05-30 06:44 UTC, jpherdi commented on index.md
> +  <td><span style="color:crimson"> ZE HS 02</span></td>
ok

2022-05-30 06:46 UTC, jpherdi commented
Okay, können das von mir aus erstmal offen lassen. Ich könnte bei Herrn Albrecht nach dem Seminarraum fragen, wenn du möchtest.

2022-05-31 06:39 UTC, chrbeckm commented
Das wäre gut, ich habe momentan keinen Zugriff auf einen Seminarraum.

2022-06-19 12:33 UTC, jpherdi approved these changes

2022-06-19 13:27 UTC, merged