redo latex full install script
pep-dortmund/homepage-toolbox pull request #189
Opened 2022-05-30 16:52 UTC by chrbeckm

- restored all LaTeX installation
- provide mini installation as help with low disk space

2022-05-30 16:55 UTC, jpherdi requested changes

2022-05-30 16:55 UTC, jpherdi commented on install/linux.md
> +herunterladen und ausgeführt.
Heruntergeladen*

2022-06-19 13:51 UTC, jpherdi approved these changes
Ich finde das so immer noch nicht perfekt, aber besser als momentan.
Sollte aber bis September noch richtig gefixed werden.

2022-06-20 06:46 UTC, chrbeckm commented
Steht auf der Agenda für das erste Vortreffen.

2022-06-20 06:46 UTC, merged