274 minimize archive
pep-dortmund/homepage-toolbox pull request #304
Opened 2024-08-02 14:18 UTC by SepplL

Refers to #274 and closes issue.

tarball all old directories as discussed in meeting.

2024-08-02 14:29 UTC, aknierim requested changes
We should remove the old (i.e. now dead) links from `archive.md`. Besides that, LGTM.

2024-08-02 14:47 UTC, SepplL commented
> We should remove the old (i.e. now dead) links from `archive.md`. Besides that, LGTM.

I was working on exactly that in the moment you commented.
I plainly linked against the tarball every time to preserve the current timestamps of editing and the daily progress.

2024-08-02 15:10 UTC, aknierim commented
Wouldn't it make more sense to just link every tarball once? Something like this (keeping the last year as is, then adding links to the tarballs):

## Wintersemester 2023/24
### Toolbox
...
### LaTeX
...

## Wintersemester 2022/23
* [Archive download] (2023.tar.gz)

## Wintersemester 2021/22
* [Archive download] (2022.tar.gz)
...

2024-08-02 15:24 UTC, aknierim approved these changes
LGTM!

2024-08-06 08:09 UTC, chrbeckm commented
Do we upload the files from the running workshop into a `current` dir then?

2024-08-06 08:19 UTC, SepplL commented
Or we initialize a new year and set the `latest` link after the workshop is finished. Then keep two years for some time and later move to only storing the tarball.
We could think of a schedule when to change the archive. A couple of months after the workshop is done maybe?

2024-09-06 17:00 UTC, SepplL commented
Now updated to include proper `current` directory with all links as discussed in the last meeting.
This should be the last change before adding the files for this year (if approved ofc)

2024-09-07 17:57 UTC, aknierim requested changes
Just a minor change and we can merge :)

2024-09-07 17:57 UTC, aknierim commented on archive.md
> +#### Alles zusammen als Archive
Maybe change "Archive" to German singular "Archiv"? This sounds somewhat off otherwise

2024-09-08 08:07 UTC, SepplL commented
Done. Renamed all `Archive` to `Archiv`.
This begs the question whether we want to offer the archives as more accessible `zip` files at some point as well?
This is no necessary change as of now, but if multiple people ask about this, it could be a viable change later down the road.

2024-09-08 08:42 UTC, aknierim commented
> This begs the question whether we want to offer the archives as more accessible `zip` files at some point as well? This is no necessary change as of now, but if multiple people ask about this, it could be a viable change later down the road.

Thought about that too. I guess this is definitely something worth considering for the future.

2024-09-08 08:43 UTC, aknierim approved these changes
Looks good :)

2024-09-09 09:03 UTC, SepplL commented
Now edited the material section to also utilize the `current` link structure as well. If there are no complaints, I would merge the current state later.

2024-09-09 13:17 UTC, aknierim approved these changes

2024-09-09 13:54 UTC, merged